# Generated by Django 6.0.6 on 2026-06-28 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_category_image_url_productimage_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image_url',
            field=models.URLField(blank=True, help_text='Vercel Blob storage URL (preferred)', max_length=600),
        ),
        migrations.AddField(
            model_name='reviewimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Vercel Blob storage URL (preferred)', max_length=600),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='image_url',
            field=models.URLField(blank=True, help_text='Vercel Blob storage URL (preferred)', max_length=600),
        ),
    ]
