# Generated by Django 6.0.6 on 2026-07-02 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_shipping_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, help_text='Saved country preference', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, help_text='Saved language preference', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductCountryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='e.g. IN, US, GB', max_length=10)),
                ('currency', models.CharField(help_text='e.g. INR, USD, GBP', max_length=10)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_prices', to='store.product')),
            ],
            options={
                'verbose_name_plural': 'Product Country Prices',
                'unique_together': {('product', 'country_code')},
            },
        ),
    ]
