# Generated by Django 6.0.6 on 2026-07-01 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_product_artisan_story_product_metal_purity'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_tracking_id',
            field=models.CharField(blank=True, help_text='Shiprocket Shipment ID / AWB', max_length=100),
        ),
    ]
