# Generated by Django 6.0.6 on 2026-07-05 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_countrysetting_default_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='town',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
