# Generated by Django 6.0.6 on 2026-07-06 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_address_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_flash_sale',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_new_arrival',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ProductAPlusContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('hero_banner', 'Hero Banner (Full-width Image Poster)'), ('feature_grid', 'Feature Highlight Grid (3 columns with icons)'), ('text_block', 'Rich Text Block'), ('image_text_left', 'Image Left + Text Right'), ('image_text_right', 'Text Left + Image Right'), ('comparison_table', 'Product Comparison Table'), ('gallery_strip', 'Image Gallery Strip')], max_length=30)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Display order (lower = first)')),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('subtitle', models.CharField(blank=True, max_length=500)),
                ('body_text', models.TextField(blank=True, help_text='Rich description text or HTML content')),
                ('image_url', models.URLField(blank=True, help_text='Main image URL (hero banner, image+text blocks)', max_length=600)),
                ('image_alt', models.CharField(blank=True, max_length=200)),
                ('bg_color', models.CharField(blank=True, default='', help_text='Background color hex, e.g. #FFD700', max_length=20)),
                ('text_color', models.CharField(blank=True, default='', help_text='Text color hex, e.g. #FFFFFF', max_length=20)),
                ('json_data', models.JSONField(blank=True, help_text='Structured data for feature grids, comparison tables, gallery strips', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplus_blocks', to='store.product')),
            ],
            options={
                'verbose_name': 'A+ Content Block',
                'verbose_name_plural': 'A+ Content Blocks',
                'ordering': ['order', 'id'],
            },
        ),
    ]
