# Generated by Django 6.0.6 on 2026-07-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_order_created_at_alter_order_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductAPlusContent',
        ),
    ]
