# Generated by Django 6.0.6 on 2026-07-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_delete_productapluscontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='aplus_image_url',
            field=models.URLField(blank=True, help_text='Upload a single long image for A+ Amazon-style content', max_length=600),
        ),
    ]
