# Generated by Django 6.0.6 on 2026-07-06 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_aplus_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
