# Generated by Django 6.0.6 on 2026-07-07 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_remove_product_subcategory_delete_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductAplusImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, help_text='Vercel Blob storage URL (preferred)', max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='aplus_products/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplus_images', to='store.product')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
