# Generated by Django 6.0.6 on 2026-07-09 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_productaplusimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for internal reference', max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='Vercel Blob/Cloudflare R2 storage URL (preferred)', max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero_panels/')),
                ('link', models.CharField(blank=True, help_text='Where should this panel redirect when clicked?', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this panel appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Panel',
                'verbose_name_plural': 'Hero Panels',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement_text', models.CharField(default='WILL YOU BE MY CUSTOMER 😍 IF YES THEN SCROLL DOWN AND BUY MY PRODUCT 🛍️', max_length=255)),
                ('marquee_text', models.TextField(default='FREE Shipping on orders above ₹499 ✦ Use Code JHUMKA10 ✦ Authentic Oxidised Silver ✦ Free Delivery Above ₹499 ✦ Use Code JHUMKA10 ✦ Authentic Oxidised Silver ✦')),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
