# Generated by Django 6.0.6 on 2026-07-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_heropanel_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerspectiveCarouselImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100)),
                ('image_url', models.URLField(blank=True, help_text='Vercel Blob/Cloudflare R2 storage URL (preferred)', max_length=600)),
                ('image', models.ImageField(blank=True, null=True, upload_to='perspective_carousel/')),
                ('link', models.CharField(blank=True, help_text='Where should this panel redirect when clicked?', max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which this image appears')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Perspective Carousel Image',
                'verbose_name_plural': 'Perspective Carousel Images',
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
