# Generated by Django 5.2.16 on 2026-07-10 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_perspectivecarouselimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heropanel',
            name='image',
        ),
    ]
