# Generated by Django 6.0.6 on 2026-07-10 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_heropanel_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerspectiveCarouselImage',
        ),
    ]
