# Generated by Django 6.0.6 on 2026-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_productquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='guest_email',
            field=models.EmailField(blank=True, help_text='Email captured during guest checkout', max_length=255, null=True),
        ),
    ]
