# Generated by Django 6.0.6 on 2026-07-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_order_guest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image_url',
            field=models.URLField(blank=True, help_text='Vercel Blob / R2 storage URL', max_length=600),
        ),
    ]
