# Generated by Django 6.0.6 on 2026-07-27 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_productvariant_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomBoxPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.CharField(choices=[('12', '12 Pairs'), ('16', '16 Pairs')], max_length=2, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in INR', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Custom Box Pricing',
                'verbose_name_plural': 'Custom Box Pricing',
            },
        ),
        migrations.CreateModel(
            name='CustomEarring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('image_url', models.URLField(help_text='Cloudflare R2 image URL', max_length=600)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Custom Earring',
                'verbose_name_plural': 'Custom Earrings',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomBoxOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box_type', models.CharField(choices=[('12', '12 Pairs'), ('16', '16 Pairs')], max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_box', to='store.order')),
                ('selected_earrings', models.ManyToManyField(related_name='custom_orders', to='store.customearring')),
            ],
            options={
                'verbose_name': 'Custom Box Order',
                'verbose_name_plural': 'Custom Box Orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
