# Generated by Django 6.0.6 on 2026-07-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_custom_earrings'),
    ]

    operations = [
        migrations.AddField(
            model_name='heropanel',
            name='background_text',
            field=models.CharField(blank=True, help_text='Text shown behind photo in hero animation (Ghost Text)', max_length=200),
        ),
        migrations.AddField(
            model_name='heropanel',
            name='bg_color',
            field=models.CharField(default='#7C1F45', help_text='Hero section background color hex e.g. #7C1F45', max_length=20),
        ),
        migrations.AddField(
            model_name='heropanel',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload image file directly from admin', null=True, upload_to='hero_panels/'),
        ),
        migrations.AddField(
            model_name='heropanel',
            name='panel_color',
            field=models.CharField(default='#9A2E5B', help_text='Secondary panel color hex e.g. #9A2E5B', max_length=20),
        ),
        migrations.AlterField(
            model_name='heropanel',
            name='image_url',
            field=models.URLField(blank=True, help_text='Vercel Blob/Cloudflare R2 storage URL (alternative)', max_length=600),
        ),
        migrations.AlterField(
            model_name='heropanel',
            name='title',
            field=models.CharField(blank=True, help_text='Title / Label (e.g. Ruby Stone Long Jhumka)', max_length=100),
        ),
    ]
