# Generated by Django 6.0.6 on 2026-07-31 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_heropanel_background_text_heropanel_bg_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customearring',
            name='name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
