# Generated by Django 6.0.6 on 2026-08-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_customearring_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='personalization_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name for Personalisation'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='personalization_name',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Name for Personalisation'),
        ),
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product', 'variant', 'personalization_name')},
        ),
    ]
