# Generated by Django 6.0.6 on 2026-08-01 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_cartitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_personalization',
            field=models.BooleanField(default=False, help_text='Explicitly allow personalisation input for this product'),
        ),
    ]
