[project]
name = "hypehavenhub"
version = "0.1.0"
description = "HypeHavenHub Store"
requires-python = ">=3.11,<3.13"
dependencies = [
    "django>=5.0,<6.0",
    "crispy-bootstrap5",
    "django-cors-headers",
    "django-crispy-forms",
    "django-storages",
    "djangorestframework",
    "djangorestframework-simplejwt",
    "gunicorn",
    "pillow",
    "psycopg2-binary",
    "python-decouple",
    "whitenoise",
    "dj-database-url",
    "razorpay",
    "requests",
    "vercel-blob",
    "django-allauth[socialaccount]",
]
