[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "crispy-bootstrap5>=2025.6",
    "django>=5.2.11",
    "django-cors-headers>=4.9.0",
    "django-crispy-forms>=2.5",
    "django-storages>=1.14.6",
    "djangorestframework>=3.16.1",
    "djangorestframework-simplejwt>=5.5.1",
    "gunicorn>=25.1.0",
    "pillow>=12.1.1",
    "psycopg2-binary>=2.9.11",
    "python-decouple>=3.8",
    "whitenoise>=6.11.0",
    "dj-database-url>=2.3.0",
    "razorpay>=2.0.1",
    "requests>=2.34.2",
    "vercel-blob>=0.4.2",
    "django-allauth[socialaccount]>=0.61.1",
]
