# Generated by Django 5.2.13 on 2026-06-18 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_flashsale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnrequest',
            name='reason',
            field=models.CharField(choices=[('damaged', 'Jewelry is Damaged'), ('wrong', 'Wrong Jewelry Delivered'), ('not_as_described', 'Not as Described'), ('expired', 'Quality Issue'), ('other', 'Other')], max_length=30),
        ),
    ]
