# Generated by Django 6.0.6 on 2026-06-28 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_productimage_image_base64_alter_productimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image_url',
            field=models.URLField(blank=True, help_text='Vercel Blob storage URL (preferred)', max_length=600),
        ),
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Vercel Blob storage URL (preferred)', max_length=600),
        ),
    ]
