# Generated by Django 6.0.6 on 2026-06-30 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_brand_image_url_reviewimage_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='artisan_story',
            field=models.TextField(blank=True, help_text='Details about the craftsmanship and origin'),
        ),
        migrations.AddField(
            model_name='product',
            name='metal_purity',
            field=models.CharField(blank=True, help_text='e.g., 18K Solid Gold, 925 Sterling Silver', max_length=100),
        ),
    ]
