# Generated by Django 6.0.6 on 2026-07-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_countrysetting_productprice_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countrysetting',
            name='default_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi (हिन्दी)'), ('zh', 'Chinese (中文)'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)'), ('ar', 'Arabic (العربية)'), ('pt', 'Portuguese (Português)'), ('de', 'German (Deutsch)'), ('ja', 'Japanese (日本語)'), ('ru', 'Russian (Русский)'), ('bn', 'Bengali (বাংলা)'), ('ur', 'Urdu (اردو)'), ('id', 'Indonesian (Bahasa Indonesia)'), ('it', 'Italian (Italiano)'), ('ko', 'Korean (한국어)'), ('tr', 'Turkish (Türkçe)'), ('vi', 'Vietnamese (Tiếng Việt)'), ('th', 'Thai (ไทย)'), ('nl', 'Dutch (Nederlands)'), ('pl', 'Polish (Polski)'), ('fa', 'Persian (فارسی)'), ('sw', 'Swahili (Kiswahili)'), ('ta', 'Tamil (தமிழ்)'), ('te', 'Telugu (తెలుగు)'), ('mr', 'Marathi (मराठी)'), ('gu', 'Gujarati (ગુજરાતી)'), ('pa', 'Punjabi (ਪੰਜਾਬੀ)'), ('ms', 'Malay (Bahasa Melayu)'), ('he', 'Hebrew (עברית)'), ('el', 'Greek (Ελληνικά)')], default='en', max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('hi', 'Hindi (हिन्दी)'), ('zh', 'Chinese (中文)'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)'), ('ar', 'Arabic (العربية)'), ('pt', 'Portuguese (Português)'), ('de', 'German (Deutsch)'), ('ja', 'Japanese (日本語)'), ('ru', 'Russian (Русский)'), ('bn', 'Bengali (বাংলা)'), ('ur', 'Urdu (اردو)'), ('id', 'Indonesian (Bahasa Indonesia)'), ('it', 'Italian (Italiano)'), ('ko', 'Korean (한국어)'), ('tr', 'Turkish (Türkçe)'), ('vi', 'Vietnamese (Tiếng Việt)'), ('th', 'Thai (ไทย)'), ('nl', 'Dutch (Nederlands)'), ('pl', 'Polish (Polski)'), ('fa', 'Persian (فارسی)'), ('sw', 'Swahili (Kiswahili)'), ('ta', 'Tamil (தமிழ்)'), ('te', 'Telugu (తెలుగు)'), ('mr', 'Marathi (मराठी)'), ('gu', 'Gujarati (ગુજરાતી)'), ('pa', 'Punjabi (ਪੰਜਾਬੀ)'), ('ms', 'Malay (Bahasa Melayu)'), ('he', 'Hebrew (עברית)'), ('el', 'Greek (Ελληνικά)')], help_text='Saved language preference', max_length=5),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('hi', 'Hindi (हिन्दी)'), ('zh', 'Chinese (中文)'), ('es', 'Spanish (Español)'), ('fr', 'French (Français)'), ('ar', 'Arabic (العربية)'), ('pt', 'Portuguese (Português)'), ('de', 'German (Deutsch)'), ('ja', 'Japanese (日本語)'), ('ru', 'Russian (Русский)'), ('bn', 'Bengali (বাংলা)'), ('ur', 'Urdu (اردو)'), ('id', 'Indonesian (Bahasa Indonesia)'), ('it', 'Italian (Italiano)'), ('ko', 'Korean (한국어)'), ('tr', 'Turkish (Türkçe)'), ('vi', 'Vietnamese (Tiếng Việt)'), ('th', 'Thai (ไทย)'), ('nl', 'Dutch (Nederlands)'), ('pl', 'Polish (Polski)'), ('fa', 'Persian (فارسی)'), ('sw', 'Swahili (Kiswahili)'), ('ta', 'Tamil (தமிழ்)'), ('te', 'Telugu (తెలుగు)'), ('mr', 'Marathi (मराठी)'), ('gu', 'Gujarati (ગુજરાતી)'), ('pa', 'Punjabi (ਪੰਜਾਬੀ)'), ('ms', 'Malay (Bahasa Melayu)'), ('he', 'Hebrew (עברית)'), ('el', 'Greek (Ελληνικά)')], default='en', max_length=5),
        ),
    ]
